import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

// Front page TODOS:
// 1 Branding: Include your platform's logo, name, and tagline to establish brand identity.
// 2 Introduction: A brief description or welcome message that highlights the purpose and benefits of using your platform
// 3 Search bar: A prominent search bar to allow users to quickly search for books by title, author, genre, or keyword.
// 4 Featured books: Showcase a selection of recently added, or staff-picked books to entice users to explore further.
// 5 Public Book Requests: Display a few recent public book requests to encourage users to fulfill them.
// 6 Sign in: A prominent sign in button to allow users to sign in with their Google account. // Logout button
// 7 How it works: Provide a brief step-by-step guide or an explainer video on how to use your book swapping platform.
// 8 Social media links: Add icons or links to your platform's social media accounts to encourage users to follow and engage with your brand.
// 9 Contact information: Include your email address and/or phone number to allow users to contact you with questions or feedback.
// 10 Terms of Service, Privacy Policy, Help Center, FAQ, and Contact Us.
export default function Home() {
  const { data: session } = useSession()

  return <>
    <Head>
      <title>Bókaskipti</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.center}>
        <Image
          className={styles.logo}
          src="/next.svg"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />
        <div className={styles.thirteen}>
          <Image
            src="/thirteen.svg"
            alt="13"
            width={40}
            height={31}
            priority
          />
        </div>
      </div>

      <div className={styles.grid}>
        <a
          href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            todo <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            This section has changed
          </p>
        </a>

        <a
          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Learn <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            Learn about Next.js in an interactive course with&nbsp;quizzes!
          </p>
        </a>

        <a
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Templates <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            Discover and deploy boilerplate example Next.js&nbsp;projects.
          </p>
        </a>

        <a
          href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          className={styles.card}
          target="_blank"
          rel="noopener noreferrer"
        >
          <h2 className={inter.className}>
            Deploy <span>-&gt;</span>
          </h2>
          <p className={inter.className}>
            Instantly deploy your Next.js site to a shareable URL
            with&nbsp;Vercel.
          </p>
        </a>
      </div>
    </main>
  </>
}
